# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "less33.yml"
  end

  config.vm.define "cluster" do |cluster|
    cluster.vm.hostname = "cluster"
    cluster.vm.network "private_network", ip: "192.168.10.5"
  end
end
