MACHINES = {
:inetRouter => {
        :box_name => "centos/7",
        #:public => {:ip => '10.10.10.1', :adapter => 1},
        :net => [
                   {ip: '1.1.1.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router-net"},
                ]
  },
:inet2Router => {
        :box_name => "centos/7",
	#:ip_addr => '192.168.55.10',
#        :hostonly => {type: "dhcp"},
        :net => [
		    #{ip: '172.28.128.8', adapter:3},
		   {type: "dhcp", adapter: 3},
                   {ip: '1.1.2.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "router2-net"},
                ]
  },
  :centralRouter => {
        :box_name => "centos/7",
        :net => [
                   {ip: '1.1.1.2', adapter: 2, netmask: "255.255.255.252", gateway: "1.1.1.1", virtualbox__intnet: "router-net"},
                   {ip: '1.1.2.2', adapter: 3, netmask: "255.255.255.252", gateway: "1.1.2.1", virtualbox__intnet: "router2-net"},
		   {ip: '192.168.0.1', adapter: 4, netmask: "255.255.255.240", virtualbox__intnet: "local"},
                ]
  },

###Servers  
  :centralServer => {
        :box_name => "centos/7",
        :net => [
                   {ip: '192.168.0.10', adapter: 2, netmask: "255.255.255.240", gateway: "192.168.0.1", virtualbox__intnet: "local"},
                ]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        
        if boxconfig.key?(:public)
          box.vm.network "public_network", boxconfig[:public]
        end

        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
        SHELL
        
        case boxname.to_s
        when "inetRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
#	    ip route add 192.168.0.0/28 via 1.1.1.2
	    sysctl net.ipv4.conf.all.forwarding=1
	    sudo yum install -y git
	    git clone https://github.com/kakunindima/sources.git
	    cd sources/less20/task1/
	    sudo cp sshd_config /etc/ssh/
	    sudo systemctl restart sshd
	    iptables-restore < iptables.rules
	    sudo useradd test
	    sudo echo 1 | passwd test --stdin
            SHELL

        when "inet2Router"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            
            iptables -t nat -A POSTROUTING ! -d 192.168.0.0/16 -o eth0 -j MASQUERADE
	    sysctl net.ipv4.conf.all.forwarding=1
	    iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
            ip route add 192.168.0.0/24 via 1.1.2.2
	    iptables -t nat -A PREROUTING -i eth2 -p tcp --dport 8080 -j DNAT --to-destination 1.1.2.2:8080
	    SHELL

        when "centralRouter"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
            systemctl restart network            
	    sysctl net.ipv4.conf.all.forwarding=1
	    iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
	    iptables -t nat -A POSTROUTING -o eth2 -j MASQUERADE
	    iptables -t nat -A POSTROUTING -o eth3 -j MASQUERADE
	    iptables -t nat -A PREROUTING -i eth2 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 192.168.0.10:80
	    sudo yum install -y git
	    git clone https://github.com/kakunindima/sources.git
	    cd sources/less20/task1/
	    
	    sudo chmod a+x knock.sh
	    sudo yum install -y nmap
	    
	    SHELL
        when "centralServer"
          box.vm.provision "shell", run: "always", inline: <<-SHELL
            echo "DEFROUTE=no" >> /etc/sysconfig/network-scripts/ifcfg-eth0 
#           echo "GATEWAY=192.168.0.1" >> /etc/sysconfig/network-scripts/ifcfg-eth1
            systemctl restart network
#	    sudo ip route add default via 192.168.0.1
	    sysctl net.ipv4.conf.all.forwarding=1
	    iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE
    	    sudo yum install -y epel-release
	    sudo yum install -y nginx
	    sudo systemctl start nginx
	    sudo yum install -y git 
	    git clone https://github.com/kakunindima/sources.git
	    cp sources/less20/task2/* /usr/share/nginx/html/
	    SHELL
       end

      end

  end
  
  
end