# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :ldap => {
        :box_name => "centos/7",
        :ip_addr => '192.168.10.2',
	:cpus => 2,
	:memory => 3072,
  },
  :cli => {
	:box_name => "centos/7",
	:ip_addr => '192.168.1.3'
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s

      box.vm.network "private_network", ip: boxconfig[:ip_addr]
      box.vm.provider :virtualbox do |vb|
	vb.customize ["modifyvm", :id, "--memory", "240"]
    end
    box.vm.provision "shell", inline: <<-SHELL
	mkdir -p ~root/.ssh
	cp ~vagrant/.ssh/auth* ~root/.ssh
	sed -i '65s/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
	sudo yum install -y epel-release
	sudo yum install -y ansible
	name=`hostname`
    SHELL

    box.vm.provision :ansible do |ansible|
	ansible.inventory_path = "inventories/all.yml"	
	ansible.limit = $name
        ansible.playbook = "less26.yml"
    end	
    end
    
  end
end

